title: Syllabus
description: Apenas um pequeno compilado de ementas e bibliografias de cursos
theme: just-the-docs
color_scheme: "light"
search_enabled: true

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
